Switch to Github Actions

diff --git a/build/.ci/scripts/lib/myFuncs b/build/.ci/scripts/lib/myFuncs
--- a/build/.ci/scripts/lib/myFuncs
+++ b/build/.ci/scripts/lib/myFuncs
@@ -61,8 +61,8 @@ persistBranchName() {
 deleteReleaseEnvs() {
 
   # Create folder to work in
-  GITDATA_FOLDER="/tmp/workspace/git_data"
-  mkdir -p GITDATA_FOLDER
+  GITDATA_FOLDER="${TEMP_DIR}/workspace/git_data"
+  mkdir -p -v "${GITDATA_FOLDER}"
 
   GIT_PR_DATA_FILE="${GITDATA_FOLDER}/git_repo_pulls.json"
   touch ${GIT_PR_DATA_FILE}
@@ -70,7 +70,7 @@ deleteReleaseEnvs() {
   echo -e ${GIT_PR_DATA_FILE}
 
   # grab github pr data and names
-  GITHUB_REPO_URL="https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pulls"
+  GITHUB_REPO_URL="https://api.github.com/repos/$CI_PROJECT_NAME/pulls"
 
   curl -s -H "Authorization: token ${GITHUB_TOKEN}" ${GITHUB_REPO_URL} > ${GIT_PR_DATA_FILE}
 
@@ -130,3 +130,24 @@ deleteReleaseEnvs() {
 mktouch() {
   mkdir -p $(dirname $1) && touch $1;
 }
+
+resolve_relative_path() (
+    # If the path is a directory, we just need to 'cd' into it and print the new path.
+    if [ -d "$1" ]; then
+        cd "$1" || return 1
+        pwd
+    # If the path points to anything else, like a file or FIFO
+    elif [ -e "$1" ]; then
+        # Strip '/file' from '/dir/file'
+        # We only change the directory if the name doesn't match for the cases where
+        # we were passed something like 'file' without './'
+        if [ ! "${1%/*}" = "$1" ]; then
+            cd "${1%/*}" || return 1
+        fi
+        # Strip all leading slashes upto the filename
+        echo "$(pwd)/${1##*/}"
+    else
+        echo "Error wtih: $1"
+        return 1 # Failure, neither file nor directory exists.
+    fi
+)
